project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - quarto/**
    
    
author:
  - name: Vagish Hemmige
    affiliations:
      - Montefiore Medical Center/ Albert Einstein College of Medicine
    email: vahemmig@montefiore.org



website:
  site-url: https://vagishhemmige.github.io/HOPE-CDC-analysis-2026
  repo-url: https://github.com/VagishHemmige/HOPE-CDC-analysis-2026
  repo-actions: [edit, issue]
  title: "Geographic Access of People Living with HIV to Solid Organ Transplant"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home

      - section: Data & Setup
        contents:
          - href: quarto/setup.qmd
            text: Setup
          - href: quarto/functions.qmd
            text: Functions

      - section: Results
        contents:
          - href: quarto/tables.qmd
            text: Tables
          - href: quarto/figures.qmd
            text: Figures

      - href: quarto/about.qmd
        text: About

  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
