project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - quarto/**
    
    
author:
  - name: Vagish Hemmige
    affiliations:
      - Montefiore Medical Center/ Albert Einstein College of Medicine
    email: vahemmig@montefiore.org



website:
  site-url: https://vagishhemmige.github.io/HOPE-CDC-analysis-2026
  repo-url: https://github.com/VagishHemmige/HOPE-CDC-analysis-2026
  repo-actions: [edit, issue]
  title: "Geographic Access of People Living with HIV to Solid Organ Transplant"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home

      - section: Data Loading & Setup
        contents:
          - href: quarto/setup.qmd
            text: Setup
          - href: quarto/functions.qmd
            text: Functions

      - section: Data Processing
        contents:
          - href: quarto/load_data.qmd
            text: Load data
          - href: quarto/classify_centers.qmd
            text: Classify centers
          - href: quarto/county_geographic_calculations.qmd
            text: County-level geographic calculations
          - href: quarto/geographical_computations_for_centers.qmd
            text: Center-level geographic calculations
          - href: quarto/set_isochrones.qmd
            text: Set isochrones
          - href: quarto/unite_buffers.qmd
            text: Unite buffers
          - href: quarto/join_tracts_to_buffers.qmd
            text: Join tracts to buffers
          - href: quarto/join_tracts_to_united_buffers.qmd
            text: Join tracts to united buffers
          - href: quarto/R/calculate_aggregated_results.qmd
            text: Calculate aggregated results

      - section: Results
        contents:
          - href: quarto/tables.qmd
            text: Tables
          - href: quarto/figures.qmd
            text: Figures

      - href: quarto/about.qmd
        text: About

  page-navigation: true

custom-callout:
  Rcode:
    icon: true
    icon-symbol: "ðŸ’» "
    color: "pink"

filters:
- custom-callout

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
    code-summary: "Click to show/hide R Code"
