project:
  type: website
  output-dir: docs



website:
  site-url: https://vagishhemmige.github.io/HOPE-CDC-analysis-2026
  repo-url: https://github.com/VagishHemmige/HOPE-CDC-analysis-2026
  repo-actions: [edit, issue]
  title: "Geographic access of people living with HIV to solid organ transplant"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: quarto/setup.html
        text: Setup
      - href: quarto/functions.html
        text: Functions
      - href: quarto/tables.html
        text: 5. Tables
      - href: quarto/figures.html
        text: 6. Figures
      - href: quarto/about.html
        text: About
        
    right:
      - icon: github
        href: https://github.com/VagishHemmige/HOPE-CDC-analysis-2026
        aria-label: GitHub repository

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
